language: elixir

elixir:
  - 1.10.3

otp_release:
  - 22.0

services:
  - postgresql

before_script:
  - mix format --check-formatted
  - MIX_ENV=test mix do event_store.create, event_store.init
  - MIX_ENV=test mix do ecto.create, ecto.migrate

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
